# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15a8006ab586aa28a1919f42de1ab40498afc5bb1ba066b74e380102577a15927122101a6a3719ff3ea2d0c4e30c2f8c54be8a129b97c79780463d9841cc9071

test:
  secret_key_base: 334e2595b8331d78ffcdc5f99fe579b3fb296105f2c832eff5732712d4467260717b09c48d53022f0ffc574a5d655a8b76940bee3f8fca081716f37a28111e93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
